/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package reloj;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Timer;

/**
 *
 * @author jonatanLara
 */
public class Ventana extends javax.swing.JFrame {
    private Timer timer;
    /**
     * Creates new form Ventana
     */
   
    public Ventana() {
        initComponents();
        horaDelSistema();
    }
    public class cronometro implements ActionListener{
        public void actionPerformed(ActionEvent evt){
            GregorianCalendar tiempo= new GregorianCalendar();
            int hora, min, seg, horario;
            int dia , mes , año;
            hora = tiempo.get(Calendar.HOUR);
            min = tiempo.get(Calendar.MINUTE);
            seg = tiempo.get(Calendar.SECOND);
            horario = tiempo.get(Calendar.AM_PM);
            
            lbH.setText(String.valueOf(hora));
            lbM.setText(String.valueOf(min));
            lbS.setText(String.valueOf(seg));
            System.out.println(""+Calendar.AM_PM);
            
           
        }
    }
    public void horaDelSistema(){
        timer = new Timer(1000, new cronometro());//Timer, delay , actionListener
        timer.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbH = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbM = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbS = new javax.swing.JLabel();
        lbS1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbH.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        lbH.setText("00");

        jLabel2.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        jLabel2.setText(":");

        lbM.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        lbM.setText("00");

        jLabel4.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        jLabel4.setText(":");

        lbS.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        lbS.setText("00");

        lbS1.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        lbS1.setText("00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbS1)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbH)
                    .addComponent(jLabel2)
                    .addComponent(lbM)
                    .addComponent(jLabel4)
                    .addComponent(lbS)
                    .addComponent(lbS1))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbH;
    private javax.swing.JLabel lbM;
    private javax.swing.JLabel lbS;
    private javax.swing.JLabel lbS1;
    // End of variables declaration//GEN-END:variables
    
}
